version: "3"
services:
  employee_service:
    restart: always
    ports:
      - 3000:3000
    environment:
      ENVIRONMENT: local
    build:
      context: ./employee-nest-graphql

  location_service:
    restart: always
    ports:
      - 3001:3001
    environment:
      ENVIRONMENT: local
    build:
      context: ./location-nest-graphql
  # graphql_fedaration:
  #   restart: always
  #   ports:
  #     - 4000:4000
  #   environment:
  #     ENVIRONMENT: local
  #   build:
  #     context: ./graphql-fedaration
